services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-swoole-crud-microservice:latest
    environment:
      APP_ENV: prod
      DB_DRIVER: mysql
      DB_DSN: mysql:host=mysql;dbname=app;charset=utf8mb4
      DB_USER: app
      DB_PASS: app
      DB_POOL_MIN: 5
      DB_POOL_MAX: 200
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_POOL_MIN: 5
      REDIS_POOL_MAX: 200
      SWOOLE_WORKER_NUM: 4
      SWOOLE_TASK_WORKER_NUM: 4
      SWOOLE_MAX_REQUEST: 10000
    ports:
      - "9501:9501"
    depends_on: [mysql, redis]
  metrics:
    build: .
    command: php public/metrics-server.php
    ports:
      - "9310:9310"
  # ws:
  #   build: .
  #   command: php public/websocket-server.php
  #   ports:
  #     - "9502:9502"
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    ports: ["3306:3306"]
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-uapp","-papp"]
      interval: 5s
      timeout: 2s
      retries: 20
  mysqld-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqld_exporter
    environment:
      # DATA_SOURCE_NAME: "root:root@(mysql:3306)/"
      - DATA_SOURCE_NAME=exporter:exporter@(mysql:3306)/
    volumes:
      - ./docker/mysql/.my.cnf:/etc/mysql/.my.cnf:ro
    command:
      - '--config.my-cnf=/etc/mysql/.my.cnf'
    ports:
      - "9104:9104"
    depends_on:
      - mysql

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
  redis:
    image: redis:7
    ports: ["6379:6379"]
  caddy:
    image: caddy:2
    ports: ["443:443","80:80"]
    volumes:
      - ./docker/Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on: [app]
