#!/bin/bash
set -e

# Use env variables
MYSQL_USER="${MYSQL_EXPORTER_USER:-exporter}"
MYSQL_PASSWORD="${MYSQL_EXPORTER_PASS:-exporter_pass}"

# Execute SQL dynamically
mysql -u root -p"$MYSQL_ROOT_PASSWORD" <<-EOSQL
DROP USER IF EXISTS '${MYSQL_USER}'@'%';
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO '${MYSQL_USER}'@'%';
FLUSH PRIVILEGES;
EOSQL
