name: run-tests

on:
    push:
    pull_request:
    schedule:
        - cron: '0 0 * * *'

jobs:
    run-tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [8.4]

        name: P${{ matrix.php }}

        steps:
            - name: Update apt
              run: sudo apt-get update --fix-missing

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                  coverage: none
                  tools: composer, cs2pr # cs2pr converts phpcs/phpstan results into PR annotations

            - name: Setup Problem Matches
              run: |
                  echo "::add-matcher::${{ runner.tool_cache }}/php.json"
                  echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: Install dependencies
              run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

            - name: Run PHPCS
              run: vendor/bin/phpcs -p ./src --encoding=utf-8 --standard=phpcs.xml --runtime-set testVersion 8.4 --parallel=1 --report=checkstyle | cs2pr

            - name: Run PHPMD
              run: vendor/bin/phpmd ./src text phpmd.xml | cs2pr

            - name: Run PHPStan
              run: vendor/bin/phpstan analyse --configuration=phpstan.neon --memory-limit=-1 --error-format=checkstyle| cs2pr

            - name: Execute tests
              run: vendor/bin/phpunit
